-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE places (
    id SERIAL PRIMARY KEY,
    title character varying(255) NOT NULL,
    type character varying(65),
    marker character varying(65),
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    geom geometry(Point,4326),
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_on timestamp without time zone NOT NULL DEFAULT now(),
    status smallint NOT NULL DEFAULT 1
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX places_pkey ON places(id int4_ops);
CREATE INDEX places_gist ON places USING GIST (geom gist_geometry_ops_2d);


-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE place_infomation (
    id SERIAL PRIMARY KEY,
    place_id integer NOT NULL REFERENCES places(id),
    description text,
    address character varying(255) NOT NULL,
    images character varying(255),
    websites character varying(55),
    rating double precision NOT NULL DEFAULT 0,
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_on timestamp without time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX place_infomation_pkey ON place_infomation(id int4_ops);


-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE tours (
    id SERIAL PRIMARY KEY,
    title character varying(255) NOT NULL,
    description text,
    route_geodata text,
    duration character varying(65),
    start_point character varying(65),
    end_point character varying(65),
    major_spots text,
    image character varying(255),
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_on timestamp without time zone NOT NULL DEFAULT now(),
    status smallint NOT NULL DEFAULT 1
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tours_pkey ON tours(id int4_ops);


-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE tour_spots (
    id SERIAL PRIMARY KEY,
    tour_id integer NOT NULL REFERENCES tours(id),
    place_id integer NOT NULL REFERENCES places(id),
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_on timestamp without time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tour_spots_pkey ON tour_spots(id int4_ops);


-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE vector_data (
    id SERIAL PRIMARY KEY,
    title character varying(255) NOT NULL,
    type character varying(65),
    area_data text,
    color character varying(65),
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    marker character varying(65),
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_on timestamp without time zone NOT NULL DEFAULT now(),
    status smallint NOT NULL DEFAULT 1
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX vector_data_pkey ON vector_data(id int4_ops);


-- DDL generated by Postico 1.5.6
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE cities (
    id SERIAL PRIMARY KEY,
    title character varying(255) NOT NULL,
    geodata text,
    create_at timestamp without time zone NOT NULL DEFAULT now(),
    modified_on timestamp without time zone NOT NULL DEFAULT now(),
    status smallint NOT NULL DEFAULT 1
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX cities_pkey ON cities(id int4_ops);
